#!/bin/bash

echo "Running pre-commit hook..."

if ! cargo fmt -- --check; then
  echo "Formatting checks failed. Please run 'cargo fmt' to fix formatting issues."
  exit 1
fi
echo "Formatting checks passed."

if ! cargo clippy -- -D warnings; then
  echo "Linting checks failed. Please fix the linting issues."
  exit 1
fi
echo "Linting checks passed."

echo "Pre-commit checks passed."
exit 0
